-- Factory for Good giving portal — schema, security, and seed
-- Paste this entire file into the Supabase SQL editor and run it once.
-- (Safe to re-run: objects are created idempotently; seed skips existing rows.)

-- ============ tables ============

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  role text not null default 'member' check (role in ('staff','member')),
  created_at timestamptz not null default now()
);

create table if not exists public.invites (
  email text primary key,
  invited_by uuid references auth.users(id),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.orgs (
  id int generated by default as identity primary key,
  data jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.org_versions (
  id bigint generated always as identity primary key,
  org_id int not null,
  data jsonb not null,
  edited_by uuid,
  edited_at timestamptz not null default now()
);

create table if not exists public.donations (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id int not null references public.orgs(id) on delete restrict,
  amount numeric not null check (amount > 0),
  gift_date date not null default current_date,
  status text not null default 'logged' check (status in ('logged','planned')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shortlist (
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id int not null references public.orgs(id) on delete cascade,
  planned numeric not null default 0,
  created_at timestamptz not null default now(),
  primary key (user_id, org_id)
);

create table if not exists public.org_comments (
  id bigint generated always as identity primary key,
  org_id int not null references public.orgs(id) on delete cascade,
  field text not null,
  body text not null,
  author uuid references auth.users(id),
  author_name text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.org_cell_notes (
  org_id int not null references public.orgs(id) on delete cascade,
  field text not null,
  body text not null,
  updated_by uuid,
  updated_at timestamptz not null default now(),
  primary key (org_id, field)
);

-- ============ helpers ============

create or replace function public.is_staff() returns boolean
language sql stable security definer set search_path = public as
$$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'staff') $$;

-- signup gate: @factoryforgood.com is staff; anyone else must be invited
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_role text;
begin
  if lower(new.email) like '%@factoryforgood.com' then
    v_role := 'staff';
  elsif exists (select 1 from public.invites where lower(email) = lower(new.email)) then
    v_role := 'member';
  else
    raise exception 'This portal is invite-only. Ask Factory for Good to invite %', new.email;
  end if;
  insert into public.profiles (id, email, role, full_name)
  values (new.id, lower(new.email), v_role, coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- org edit history
create or replace function public.record_org_version() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.org_versions (org_id, data, edited_by) values (old.id, old.data, auth.uid());
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end $$;

drop trigger if exists on_org_updated on public.orgs;
create trigger on_org_updated
  before update on public.orgs
  for each row execute function public.record_org_version();

create or replace function public.touch_donation() returns trigger
language plpgsql as $$ begin new.updated_at := now(); return new; end $$;
drop trigger if exists on_donation_updated on public.donations;
create trigger on_donation_updated before update on public.donations
  for each row execute function public.touch_donation();

-- collective totals members may see without reading each other's rows
create or replace function public.network_alloc()
returns table (org_id int, total numeric, donors bigint)
language sql stable security definer set search_path = public as
$$ select org_id, sum(amount), count(distinct user_id)
   from public.donations where status = 'logged' group by org_id $$;

create or replace function public.network_members()
returns bigint language sql stable security definer set search_path = public as
$$ select count(*) from public.profiles where role = 'member' $$;

-- ============ row-level security ============

alter table public.profiles enable row level security;
alter table public.invites enable row level security;
alter table public.orgs enable row level security;
alter table public.org_versions enable row level security;
alter table public.donations enable row level security;
alter table public.shortlist enable row level security;
alter table public.org_comments enable row level security;
alter table public.org_cell_notes enable row level security;

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select
  using (id = auth.uid() or public.is_staff());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update
  using (id = auth.uid()) with check (id = auth.uid() and role = (select role from public.profiles p where p.id = auth.uid()));

drop policy if exists invites_staff on public.invites;
create policy invites_staff on public.invites for all
  using (public.is_staff()) with check (public.is_staff());

drop policy if exists orgs_read on public.orgs;
create policy orgs_read on public.orgs for select using (auth.role() = 'authenticated');
drop policy if exists orgs_write on public.orgs;
create policy orgs_write on public.orgs for insert with check (public.is_staff());
drop policy if exists orgs_update on public.orgs;
create policy orgs_update on public.orgs for update using (public.is_staff()) with check (public.is_staff());
drop policy if exists orgs_delete on public.orgs;
create policy orgs_delete on public.orgs for delete using (public.is_staff());

drop policy if exists versions_staff_read on public.org_versions;
create policy versions_staff_read on public.org_versions for select using (public.is_staff());

drop policy if exists donations_own on public.donations;
create policy donations_own on public.donations for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists donations_staff_read on public.donations;
create policy donations_staff_read on public.donations for select using (public.is_staff());

drop policy if exists shortlist_own on public.shortlist;
create policy shortlist_own on public.shortlist for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists comments_staff on public.org_comments;
create policy comments_staff on public.org_comments for all
  using (public.is_staff()) with check (public.is_staff());

drop policy if exists cell_notes_staff on public.org_cell_notes;
create policy cell_notes_staff on public.org_cell_notes for all
  using (public.is_staff()) with check (public.is_staff());

-- ============ seed (appended below by build script) ============
